import { MOLECULE_DEMO } from '@/artifacts/molecule/constants';
import { DocumentArtifactKind } from '@/lib/enums';

const predictedProperties = {
  '[GHS] Acute Toxicity': { prob: 83, confidence: 1.0 },
  '[GHS] Carcinogenicity': { prob: 98, confidence: 1.0 },
  '[GHS] DART': { prob: 99, confidence: 1.0 },
  '[GHS] Eye Irritation': { prob: 12, confidence: 0.5 },
  '[GHS] Skin Corrosion/Irritation': { prob: 14, confidence: 0.375 },
  '[GHS] Skin Sensitization': { prob: 58, confidence: 0.25 },
  '[GHS] STOT SE: Cardiovascular Toxicity': { prob: 85, confidence: 0.625 },
  '[GHS] STOT SE: Liver Toxicity': { prob: 96, confidence: 1.0 },
  '[GHS] STOT SE: Neurological Toxicity': { prob: 99, confidence: 1.0 },
  'Cellular Activity': { prob: 47, confidence: 1.0 },
  'Ecological Activity': { prob: 1, confidence: 1.0 },
  'Endocrine Activity': { prob: 100, confidence: 1.0 },
  'Enzyme Activity': { prob: 99, confidence: 1.0 },
  'Immune Activity': { prob: 98, confidence: 1.0 },
  'Metabolic Activity': { prob: 37, confidence: 1.0 },
  'Stress Response': { prob: 67, confidence: 1.0 },
  Mutagenicity: { prob: 84, confidence: 0.875 },
};

const pdbDataObject = {
  header: {
    proteinBinding: 'PROTEIN BINDING',
    date: '01-JAN-20',
    code: '6XYZ',
  },
  title: 'STRUCTURE OF PROTEIN XYZ',
  atoms: [
    {
      atomId: 1,
      atomName: 'N',
      residue: 'ALA',
      chain: 'A',
      residueId: 1,
      x: 11.804,
      y: 18.255,
      z: 17.872,
      occupancy: 1.0,
      temperatureFactor: 36.88,
      element: 'N',
    },
    {
      atomId: 2,
      atomName: 'CA',
      residue: 'ALA',
      chain: 'A',
      residueId: 1,
      x: 11.804,
      y: 17.364,
      z: 16.715,
      occupancy: 1.0,
      temperatureFactor: 37.78,
      element: 'C',
    },
    {
      atomId: 3,
      atomName: 'C',
      residue: 'ALA',
      chain: 'A',
      residueId: 1,
      x: 10.877,
      y: 16.181,
      z: 16.946,
      occupancy: 1.0,
      temperatureFactor: 34.62,
      element: 'C',
    },
    {
      atomId: 4,
      atomName: 'O',
      residue: 'ALA',
      chain: 'A',
      residueId: 1,
      x: 10.431,
      y: 15.933,
      z: 18.06,
      occupancy: 1.0,
      temperatureFactor: 30.65,
      element: 'O',
    },
    {
      atomId: 5,
      atomName: 'CB',
      residue: 'ALA',
      chain: 'A',
      residueId: 1,
      x: 13.232,
      y: 16.884,
      z: 16.46,
      occupancy: 1.0,
      temperatureFactor: 38.34,
      element: 'C',
    },
    {
      atomId: 6,
      atomName: 'N',
      residue: 'GLY',
      chain: 'A',
      residueId: 2,
      x: 8.928,
      y: 15.328,
      z: 15.93,
      occupancy: 1.0,
      temperatureFactor: 32.33,
      element: 'N',
    },
    {
      atomId: 7,
      atomName: 'CA',
      residue: 'GLY',
      chain: 'A',
      residueId: 2,
      x: 8.558,
      y: 14.12,
      z: 16.599,
      occupancy: 1.0,
      temperatureFactor: 30.52,
      element: 'C',
    },
    {
      atomId: 8,
      atomName: 'C',
      residue: 'GLY',
      chain: 'A',
      residueId: 2,
      x: 7.255,
      y: 14.194,
      z: 17.344,
      occupancy: 1.0,
      temperatureFactor: 27.39,
      element: 'C',
    },
    {
      atomId: 9,
      atomName: 'O',
      residue: 'GLY',
      chain: 'A',
      residueId: 2,
      x: 6.672,
      y: 13.159,
      z: 17.667,
      occupancy: 1.0,
      temperatureFactor: 26.01,
      element: 'O',
    },
    {
      atomId: 10,
      atomName: 'N',
      residue: 'ASP',
      chain: 'A',
      residueId: 3,
      x: 6.781,
      y: 15.35,
      z: 17.737,
      occupancy: 1.0,
      temperatureFactor: 24.17,
      element: 'N',
    },
    {
      atomId: 11,
      atomName: 'CA',
      residue: 'ASP',
      chain: 'A',
      residueId: 3,
      x: 5.577,
      y: 15.533,
      z: 18.503,
      occupancy: 1.0,
      temperatureFactor: 22.03,
      element: 'C',
    },
    {
      atomId: 610,
      atomName: 'O',
      residue: 'HOH',
      chain: 'A',
      residueId: 77,
      x: 20.857,
      y: 40.179,
      z: 26.62,
      occupancy: 1.0,
      temperatureFactor: 35.55,
      element: 'O',
    },
    {
      atomId: 611,
      atomName: 'O',
      residue: 'HOH',
      chain: 'A',
      residueId: 78,
      x: 21.897,
      y: 26.59,
      z: 16.13,
      occupancy: 1.0,
      temperatureFactor: 51.69,
      element: 'O',
    },
  ],
};

export const pbdPayloadJsonString: string = JSON.stringify(
  pdbDataObject,
  null,
  2,
);

export const createMoleculeDemo = (): string => {
  return `create a document with title "${MOLECULE_DEMO} ${new Date().toISOString()}"`;
};

export const predictedPropertiesJsonString: string = JSON.stringify(
  predictedProperties,
  null,
  2,
);

export const documentDemoParts = [
  {
    type: DocumentArtifactKind.PREDICTED_PROPERTIES,
    data: predictedProperties,
  },
  { type: DocumentArtifactKind.PBD_Data, data: pdbDataObject },
];

export const chatDemoParts: Array<{
  type: 'text';
  text: string;
}> = [
  { type: 'text', text: predictedPropertiesJsonString },
  { type: 'text', text: pbdPayloadJsonString },
];
